{% set name = "foundry-compute-modules" %} 
{% set version = "0.24.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/palantir/python-compute-module/archive/{{ version }}.tar.gz
  sha256: 463c8454750c5f21982221fa41ef69cc4e48f8f550280c527a9da49fd035e838

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - requests >=2.32.3

test:
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - compute_modules

about:
  home: https://github.com/palantir/python-compute-module
  summary: The official Python library for creating Compute Modules
  license: Apache-2.0
  license_family: Apache
  # See https://github.com/palantir/python-compute-module/blob/develop/LICENSE.txt
  license_file: LICENSE.txt
  doc_url: https://www.palantir.com/docs/foundry/compute-modules/overview
  dev_url: https://github.com/palantir/python-compute-module


extra:
  recipe-maintainers:
    - amazr
    - lauraAriasFdez
    - scottkruyswyk
