{% set name = "foundry-compute-modules" %} 
{% set version = "0.27.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/palantir/python-compute-module/archive/{{ version }}.tar.gz
  sha256: b05c1e251c2bc2e6c2112f55a25c5d5255991dcaaf450173ebd015252bc57cf2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - requests >=2.32.3

test:
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - compute_modules

about:
  home: https://github.com/palantir/python-compute-module
  summary: The official Python library for creating Compute Modules
  license: Apache-2.0
  license_family: Apache
  # See https://github.com/palantir/python-compute-module/blob/develop/LICENSE.txt
  license_file: LICENSE.txt
  doc_url: https://www.palantir.com/docs/foundry/compute-modules/overview
  dev_url: https://github.com/palantir/python-compute-module


extra:
  recipe-maintainers:
    - amazr
    - lauraAriasFdez
    - scottkruyswyk
